# Generated by Django 4.2.5 on 2023-10-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='data',
            field=models.DateTimeField(verbose_name='date login'),
        ),
    ]
